### ISSUE TITLE
admin-client: Legacy dependancy for @vue/cli-plugin-eslint at the moment

### ISSUE THREAD

**Issue by cheburan** [MRC-Epid-it24/intake24#6]
**Admin-Client:**
If installed from scratch, the current version of `eslint` package is `7.15.0`. However, `@vue/cli-plugin-eslint` requires the version  between `>= 1.6.0 < 7.0.0`. 

During the `npm install` had the following: 
```
npm ERR! Could not resolve dependency:
npm ERR! peer eslint@">= 1.6.0 < 7.0.0" from @vue/cli-plugin-eslint@4.5.9
npm ERR! node_modules/@vue/cli-plugin-eslint
npm ERR!   dev @vue/cli-plugin-eslint@"^4.5.9" from the root project
```

Not sure if it's better to downgrade (for now) to `6.8.0` in the `package.json` or follow the npm advice and `--force`, or `--legacy-peer-deps` flags for `npm install` command.

**Comment by lukashroch** [comment]
I've been using eslint 7 for quite a while with few projects with no issues. I think npm only warns during install, but eslint7 works with fine with vue.

I wonder if it's something platform specific ... `npm install` shouldn't install peer deps by itself. It's up to user to do it manually. Unless you're using recent npm7. I think that changed in npm7 and tries to install all peer deps.

**Comment by cheburan** [comment]
yep, you're right, it was npm 7.  
tested on `npm 6` no issues there. 
Thank you! 
I guess something to keep in mind.
